name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy the README.md into the chart
        run: |
          cp README.md charts/wazuh-manager-filebeat

      - name: Configure Git and add file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add charts/wazuh-manager-filebeat/README.md
          git commit --all --message "Syncs the chart's README.md"

      - name: Push the updated README.md
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}